apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-key-purge-9000
spec:
  schedule: "0 3 15 * *"  # Runs on the 15th of each month at 3 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: vault-key-purge-9000
              image: ghcr.io/dekeyrej/recryptonator-image:latest  # Replace with your container image
              imagePullPolicy: Always
              securityContext:
                privileged: false
              env:
                - name: VALIDATE
                  value: "1"
                - name: REQUESTS_CA_BUNDLE
                  value: "/etc/ssl/certs/internal-ca.pem"
              volumeMounts:
                - name: secretcfg-volume
                  mountPath: /code/secretcfg.json
                  subPath: secretcfg.json
                - name: secretdef-volume
                  mountPath: /code/secretdef.json
                  subPath: secretdef.json
                - name: ca-volume
                  mountPath: /etc/ssl/certs/internal-ca.pem
                  subPath: ca.pem
          restartPolicy: OnFailure
          volumes:
            - name: secretcfg-volume
              configMap:
                name: secretcfg
            - name: secretdef-volume
              configMap:
                name: secretdef
            - name: ca-volume
              configMap:
                name: internal-ca-cert
          imagePullSecrets:
            - name: ghcr-login-secret
